### ISSUE TITLE
Add lazyComp for easy non-rerendered component

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#105]
Similarly to Fable.React's [lazyView](https://elmish.github.io/react/common.html), we should have a function to easily create a component whose view function doesn't need to be called if the model hasn't changed. Currently this requires creating a Component class.

Proposed API mirroring Fable's:

```fsharp
val lazyComp
     : viewFunction: ('model -> Node)
    -> 'model -> Node
    when 'model : equality

val lazyCompWith
     : equal: ('model -> 'model -> bool)
    -> viewFunction: ('model -> Node)
    -> 'model -> Node

val lazyComp2
     : viewFunction: ('model -> Dispatch<'msg> -> Node)
    -> 'model -> Dispatch<'msg> -> Node
    when 'model : equality

val lazyComp2With
     : equal: ('model -> 'model -> bool)
    -> viewFunction: ('model -> Dispatch<'msg> -> Node)
    -> 'model -> Dispatch<'msg> -> Node

val lazyComp3
     : viewFunction: ('model1 -> 'model2 -> Dispatch<'msg> -> Node)
    -> 'model1 -> 'model2 -> Dispatch<'msg> -> Node
    when 'model1 : equality and 'model2 : equality

val lazyComp3With
     : equal: (('model1 * 'model2) -> ('model1 * 'model2) -> bool)
    -> viewFunction: ('model1 -> 'model2 -> Dispatch<'msg> -> Node)
    -> 'model1 -> 'model2 -> Dispatch<'msg> -> Node
```

**Comment by brikken** [comment]
Elm also has [lazy rendering](https://guide.elm-lang.org/optimization/lazy.html)
Perhaps a similar approach, with memoized nodes, could by applied in Bolero?

**Comment by Tarmil** [comment]
@brikken Wrapping a view function in a Component class basically tells Blazor to do just that. These `lazyComp` functions would just be shorthands for wrapping a view in a Component class.

**Comment by brikken** [comment]
@Tarmil I've been looking into this tonight, and I've found this snippet from the [Component docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)

> If you're unable to avoid manual RenderTreeBuilder logic, split long blocks of code into smaller pieces wrapped in OpenRegion/CloseRegion calls. Each region has its own separate space of sequence numbers, so you can restart from zero (or any other arbitrary number) inside each region.

What if the ```lazyComp``` wrapped the output of the ```viewFunction``` in a new, say ```Lazy```, union in the ```Node``` type. In the ```renderNode```function, the contents would be wrapped in an OpenRegion/CloseRegion frame. With the model unchanged, the sequence numbers inside node should remain unchanged and in turn not produce any changes in the tree diff.

One thing can might break this idea is if the sequence numbers before the lazy node has changed. That would probably cause a delete and insert even on the otherwise unchanged node.

**Comment by Tarmil** [comment]
Ha! I hadn't even seen that sequence numbers were now properly documented.

I'll read and experiment more with `OpenRegion`/`CloseRegion`, it may indeed be better than using a component.

> One thing that might break this idea is if the sequence numbers before the lazy node have changed. That would probably cause a delete and insert of the the otherwise unchanged node.

The sequence numbers should always be the same provided that you're careful to always use `cond` and `forEach` rather than manually building lists of nodes or attributes.

**Comment by brikken** [comment]
So, apparently, ForEach is already using an `OpenRegion`/`CloseRegion` frame. Currently it's using the `AddContent` method, which is implemented as
```
        public void AddContent(int sequence, RenderFragment fragment)
        {
            if (fragment != null)
            {
                // We surround the fragment with a region delimiter to indicate that the
                // sequence numbers inside the fragment are unrelated to the sequence numbers
                // outside it. If we didn't do this, the diffing logic might produce inefficient
                // diffs depending on how the sequence numbers compared.
                OpenRegion(sequence);
                fragment(this);
                CloseRegion();
            }
        }
```
However, the `ForEach` performance is far from as good as using the `ElmishComponent`, so `OpenRegion`/`CloseRegion` is probably not the way to go.

**Comment by brikken** [comment]
I've worked my way through RenderTreeDiffBuilder.cs and as far as I can see the only way to escape a full tree diff calculation is by using components. Even regions will have all their children compared no matter what. The only place in Blazor to conditionally control rendering is for a component to simply not send itself for rendering (see `ComponentBase.StateHasChanged()`), as it is currently implemented in `ElmishComponent`.

This is a shame since I can't help thinking (but not actually prove currently) that adding components liberally could incur some overhead in contrast to a simple `PerformDiff = false` flag on a `RenderTreeFrame`.

**Comment by brikken** [comment]
Creating components from a function is a challenge. The `RenderTreeBuilder` receives a `Type`, not an instance of the component. In turn, the renderer instantiates this type and injects services when applicable. As far as I can see, this leaves us with two alternatives.

## 1: Create new types at run-time
Each call to `lazy*` defines a new type at run-time using `System.Reflection.Emit`. This method requires some form of caching and matching of previously created types; otherwise a new type would be created in each update cycle for the same lazy view. This would remove the old and createa a new component, effectively causing a re-render.

## 2: One type for all lazy views
One new type is created, shared by all lazy views. The type has a new `ILazyService` injected at initialization from which it extracts view function, dispatch, etc.. However, I don't think a new component receives attribute values before initialization so at this point the type has no idea what specific role to play and thus what to request from `ILazyService`.

**Comment by brikken** [comment]
It's finally clear to me that the entire rendering process hinges on the sequence numbers being predictable throughout the lifetime of the application. Based on this I believe solution proposal 1 can be easily implemented with a `Dictionary<int,Type>`. At the first render, when the type is not found, it will be created and added to the dictionary.

**Comment by Tarmil** [comment]
I was thinking we can simply have a single Component type for all lazy views, which receives the view function as a `[<Parameter>]`. It can even simply inherit from `ElmishComponent`, which already has everything needed besides this parameter.

**Comment by brikken** [comment]
Haha, yes, I was just thinking the exact same thing. Oh well, at least my understanding of both Blazor and Bolero has increased immensely during all this.

I'll give it a try with an implementation of that tomorrow.

**Comment by brikken** [comment]
I've implemented the first 4 of the 6 signatures above using the method discussed. Spin up the test project 'Client' and go to the new Lazy page. For a demo. No further tests have been written. Any ideas and inputs for more robust testing is welcome.

I've typed the component parameters a bit but it's work in progress. Next step is to parameterize the `ComponentParameter` cases with a type and put a member constraint on that type in the component functions in Html.fs. This should provide a sort of compile time type safety that is otherwise not present when passing component parameters.

**Comment by brikken** [comment]
@Tarmil If you could provide feedback if this implementation is going in the right direction, it would be much appreciated.

In addition, I've been looking into if it's possible to auto-key the component elements to ensure further optimization when you have `lazyComp` inside a `forEach` and elements are added/deleted/re-ordered. When default equality is used and the model is a reference type, the model itself can be used as key. I don't have any ideas as to what do to if those criteria are not satisfied.

**Comment by brikken** [comment]
@Tarmil Thank you for the feedback. I've made changes accordingly, added the last two signatures, added an additional example showcasing custom equality, and created a pull request with all the changes.
