### ISSUE TITLE
Status 500 when opening a page directly which uses third-party components

### ISSUE THREAD

**Issue by AlexBoehm** [fsbolero/Bolero#157]
I experience problems when using third-party components like Blazorise. The template for Bolero contains three pages. I can directly open each url in the browser (without navigating via the menu). For example I can open /counter in the browser.

It seems that this is not working when you use other components like Blazorise or the ones from Syncfusion. When I open the url containing a Blazorise component, I always get a 500 response from the server. If I use a link to navigate to the page it is working.

In order to demonstrate this, I created a small demo project. I started it with the Bolero template and added a new page with a Blazorise button. You can find it at https://github.com/AlexBoehm/BoleroBlazorised/commit/9281e941fd8b7cf50355b056daad0f98c899394f#diff-6ce7c188ee60508fb564ccb32ccaa6dd

If you open the url /blazorise without using the nav bar, you can see the error. In contrast to this, If you start at / and navigate to /blazorise via the nav bar the page is working.

I tried the same with the C# WebAssembly Blazor template. It is working with that.

**Comment by Tarmil** [comment]
This seems to be an issue with prerendering. The Blazorise component fails to render on the server-side, which indeed only happens when you navigate directly to a page that contains it. I can see this error in the server output:

```
System.InvalidOperationException: Cannot provide a value for property 'ComponentMapper' on type 'Blazorise.Button'. There is no registered service of type 'Blazorise.IComponentMapper'.
```

Presumably some of the Services setup done in the client-side Main also needs to be done in the server-side Startup for this to work.

Alternatively, you can deactivate prerendering by replacing `.AddBoleroHost()` with `.AddBoleroHost(prerendered = false)` in ConfigureServices.

**Comment by AlexBoehm** [comment]
Thanks so much. I added the Service registration to the server as well and with that is working now.

```
services
.AddBlazorise(fun options -> 
    options.ChangeTextOnKeyPress <- true
    ()
)
.AddBootstrapProviders()
```
I also tried to to deactivate perendering as you suggested. This is working as well.

By the way, coming from React with Redux I like Bolero a lot!
