### ISSUE TITLE
Blazor 3.2.1 (brotli precompression)

### ISSUE THREAD

**Issue by wilsoncg** [fsbolero/Bolero#171]
I notice the blazor docs refer to brotli precompression, from what I can gather this was introduced in 3.2.0-preview4 [blazor-webassembly-3-2-0-preview-4-release-now-available](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/). I have tried a dotnet publish with Bolero v0.14.16, but I am not seeing the .dll.br output. I notice Bolero is using Microsoft.AspNetCore.Components.WebAssembly v.3.2.0, so this would explain why the brotli compressed files are missing from the build output.

Is there a plan to upgrade Bolero to Blazor v3.2.1?

**Comment by Tarmil** [comment]
The problem is specifically with Microsoft.AspNetCore.Components.WebAssembly.Build 3.2.1 which causes fsbolero/Template#25. All the other packages can be updated to Blazor 3.2.1, but it does mean no brotli precompression for now unfortunately.

I think the issue is the same as dotnet/aspnetcore#24109, and someone on that thread said that 5.0-preview7 fixed the issue for them, so that's worth looking into.

**Comment by wilsoncg** [comment]
@Tarmil thanks for looking into, I'm happy to close this for now and wait until blazor v5.0 ships, I'd much rather keep the stability we have currently with blazor 3.2.0 & bolero 0.14.16
