### ISSUE TITLE
Question: How to bind disabled attribute to boolean result

### ISSUE THREAD

**Issue by codec-abc** [fsbolero/Bolero#190]
Hi guys,

I am discovering Bolero and so far I really like it. I don't have really much experience into this area. Documentation and API is really nice and so far I can say it was easy to do what I want. Yet, something that seems really easy to do puzzle me. I have a piece of HTML that binds two input checkbox to 2 boolean in my model using [HTML templates and holes](https://fsbolero.io/docs/Templating#holes).

Basically, I have something like this

````html
<input class="checkbox" type="checkbox" bind="${bool1}" />
<input class="checkbox" type="checkbox" bind="${bool2}" />
````
My model is correctly and so far everything works fine. What I want to do is to have a 3rd input that is disabled when the first checkbox is checked and when the second is not checked.

I tried something like this:
````html
<input class="range" type="range" disabled="${bool1 && !bool2}" />
````

but it didn't work. I tried several things based on the help I found online but so far no luck. Can you give me some help about how to achieve this?

Thanks.

**Comment by laenas** [comment]
Note that unlike other frameworks on the web where the value inside a binding is evaluated as an expression, in Bolero (see: https://fsbolero.io/docs/Templating) the holes notated by ${SomeName} are fillable in the F# by calling .SomeName() on the template hole.
In the case of your bind's, they'd need an expression to resolve the state, and a function to resolve what happens when they are interacted with.  In the case of disabled, simply the value you're looking for.

**Comment by codec-abc** [comment]
Thanks a lot!

It seems obvious now that you have explained it now. I probably got lost when reading the stackoverflow question: [How to enable/disable inputs in blazor](https://stackoverflow.com/questions/55002514/how-to-enable-disable-inputs-in-blazor).
