### ISSUE TITLE
Problem with getting component Ref in button click handler after change in model value 

### ISSUE THREAD

**Issue by renjithsingh-rajendran123** [fsbolero/Bolero#199]
Please find the attachment sample for issue reproducing demo.

Sample : https://github.com/renjithsingh-rajendran123/BoleroF-_issue

1. Start Bolero: # dotnet run -p src/FSharp.Bolero.Server
2. Navigate to http://localhost:5000
3. Click on the button
4. First time the browser console will display "Refreshing this component!" message.
5. Again click on the button won't display the message( "Refreshing this component!").

**Comment by Tarmil** [comment]
I believe this is because the reference itself must be defined in a component class. When you put it in a function like this, it gets recreated every time the function is called, so you get this kind of behavior. You need something like this:

```fsharp
type ViewComponent() =
    inherit ElmishComponent()

    let myComponentRef = Ref<MyComponent>()

    override _.View model dispatch =
        Main()
            .Grid(
                comp<MyComponent> [attr.ref myComponentRef] []
            ).ExportToExcel(
                div [] [
                    button [on.click (fun _ -> dispatch <| ExportExcel myComponentRef.Value)] [text "Refresh MyComponent"]
                ]
            ).Elt()

let view model dispatch = ecomp<ViewComponent,_,_> model dispatch
```

I'll try to make this clearer in the documentation.

**Comment by MichaelMay81** [comment]
Isn't the problem, that MyComponent gets cached and therefore the Ref is not getting updated, but the button is updated and gets the new myComponentRef every time?

Putting the Ref inside a component fixes this problem, but isn't that a bit general to put it in the documentation as a general rule?

**Comment by MichaelMay81** [comment]
A more functional approach would be to put the Ref inside the model. This prevents it from being reinitialized. You wouldn't even need to pass it to the update function with an event.

**Comment by MichaelMay81** [comment]
I did some more debugging and it is really a bit weird. Either I am still missing something or there is some Blazor trickery going on :)
If the Refs are only declared locally in the view it works for me at the beginning, but I can reproduce an error that messes the Refs up and they seem to get partly overwritten. Forcing a rerender of the components seem to help, but the system seems not to like it, that I constantly recreate the Refs.

Putting the Refs in the Model seems to work w/o a problem. But it is important, that if you use the same component multiple times, that they all get their own Refs. So instead of "init: Model" you need an "init: unit -> Model".

I would recommend putting the Refs inside the Model instead of a Component.
For the documentation I would hint that the Refs need to be more permanent and that the Model or a Component would be sufficient.
