### ISSUE TITLE
Why not create nodes by List.map?

### ISSUE THREAD

**Issue by Martin521** [fsbolero/Bolero#224]
The [documentation](https://fsbolero.io/docs/HTML#collection-elements) warns against using `List.map` to create a list of Nodes and recommends `forEach` instead. Why is this? As far as I can see, `forEach `creates the list in a way that does not differ from how `List.map` would do it.
(I do understand the need for using `cond`, inserting an `empty` node instead of just dropping a node.)

**Comment by Tarmil** [comment]
It's a bit complicated, but it's due to the way Blazor's rendering algorithm works. In short, each insertion is associated with a sequence number. These numbers must be consistent between two consecutive renders for the algorithm to work. If you insert items using something like `List.map`, then as soon as the list has changed length between two consecutive renders, the sequence numbers will be inconsistent. `forEach` fixes the issue by wrapping the content in a `RenderFragment` with a sequence that resets for each item.

**Comment by Martin521** [comment]
Thank you for the fast reply. It seems then that in my case (lists of constant length) I can ignore it.
(Perhaps the documentation should say "... rendering collections _of unknown length_ using a function such as ...".)
BTW Bolero is really great, thanks for creating and sharing it.

**Comment by akhansari** [comment]
Related question:
Does it make sense a helper like this in order to have the index?
```fsharp
let forEachi (items: 'T list) (mkNode: int32 -> 'T -> Node) : Node =
    forEach [0..items.Length-1] (fun i -> mkNode i items.[i])
```

**Comment by Tarmil** [comment]
@akhansari It makes sense, although this implementation is not really optimal, because `items.[i]` on a list needs to go through the list to find the item. I would suggest something like this instead:

```fsharp
let forEachi items mkNode =
    forEach (Seq.mapi mkNode items) id
```
