### ISSUE TITLE
feature request: Support SignalR based data subscriptions without affecting hot reloading

### ISSUE THREAD

**Issue by fwaris** [fsbolero/Bolero#300]
Please see this issue for reference: #289 

Bolero is ideal for building live dashboards - where UI is updated without any user action. 

Useful for monitoring stats / ML model results over online data streams (among other use cases).

If SignalR is used for application data, hot reloading stops working (which currently uses SignalR under the covers).

**Comment by Tarmil** [comment]
I've revisited my attempt at using Elmish.Bridge for this purpose, and I realized that it wasn't working due to errors on my side, not any incompatibility. So as it turns out, you *can* use Elmish.Bridge with Bolero! My quick experiment is [in this repository](https://github.com/Tarmil/TestBoleroElmishBridge).

I've also tried HotReload with it and it seems to be working fine as well. My guess is that this is because Elmish.Bridge doesn't use SignalR but a direct WebSocket, so there is no friction with HotReload's SignalR connection.
