### ISSUE TITLE
[C# interop] Adding Bolero to ASP.NET Core project in C# is not friendly

### ISSUE THREAD

**Issue by xperiandri** [fsbolero/Bolero#313]
It is better to switch to .NET-compatible optional parameters for this public API.
I mean all related to building the host, services, endpoints etc.

**Comment by granicz** [comment]
Can you paste here your proposal? Thanks!

**Comment by Tarmil** [comment]
This seems reasonable. I think also that taking `Func` and `Action` arguments instead of F# functions would be similarly helpful. You can still pass an F# lambda and it will be implicitly converted to these types.

As far as I can tell, these methods would need to be converted:
* `IServiceCollection.AddBoleroHost`
* `IServiceCollection.AddBoleroRemoting` (and its many overloads, both client-side and server-side)
* `IEndpointRouteBuilder.MapFallbackToBolero`

@xperiandri Do you have any others in mind?

**Comment by xperiandri** [comment]
Also, question mark parameters.
We can rewrite as
``` F#
static member AddBoleroHost(this: IServiceCollection, [<OptionalParameter>] server: bool voption, [<OptionalParameter>] prerendered: bool voption, [<OptionalParameter>] devToggle: bool voption) =
```
Then you can either omit the parameter or pass `ValueOption.ValueSome` with a value.
The default value will become `ValueOption.ValueNone` as it is a struct.

Same thing will work with `Option` as well, but accept `null` too

**Comment by Tarmil** [comment]
I think we can even go for the simpler `[<OptionalParameter>] server: bool`, with an additional `[<DefaultParameterValue true>]` for the ones that are true by default.
