### ISSUE TITLE
Context and Authentication does not work with Remoting when hosted on  server-side.

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#70]
When we use server-side hosting, http parameter becomes null for the call back of Remote.withContext. 

Also Remote.authorize still triggers the callback despite the user has not logged in. 

Finally, singing out is also causing a problem that the runtime complains it cannot write to response because the response has already been started.

**Comment by OnurGumus** [comment]
I would even say, we don't need Remote.withContext, we could instead inject IHttpContextAccessor to the remote service since it supports dependency injection.

**Comment by Tarmil** [comment]
I just committed a fix that provides the HttpContext via Remote.withContext and the authorization via Remote.authorize.

Authentication is actually quite limited at least for the cookie provider, since that is unable to log in/out during the lifetime of the websocket. So you are always authorized according to whatever identity you had when you first opened the page. I don't know if other authentication providers are able to act on an already open SignalR websocket.

For HttpContext, you're right that we don't necessarily need Remote.withContext and could just have everyone use IHttpContextAccessor directly. I'll open a separate discussion, as it's tangential to server-side mode.
