### ISSUE TITLE
Respect HTTP Status Code

### ISSUE THREAD

**Issue by kos59125** [fsbolero/Bolero#71]
It looks like that remoting ignores server-side status code except for 200 and 401. Is there any reason not to handle error response on client-side?

**Comment by Tarmil** [comment]
I'm guessing you set the status code explicitly in your remote function using the `HttpContext`?

It's not supported because it's a use case I hadn't thought about 😄 We could just raise a different exception [here](https://github.com/fsbolero/Bolero/blob/1ac493883d7b1a52262052a20a1e25ff7461d386/src/Bolero/Remoting.Client.fs#L135) that contains the `HttpResponseMessage`, so that you can retrieve the status code from it.

**Comment by granicz** [comment]
Sounds good to me, good catch @kos59125 - thanks!
