### ISSUE TITLE
Unknown issue while refactoring the sample code. 

### ISSUE THREAD

**Issue by kunjee17** [fsbolero/Bolero#78]
I was trying to refactor code. It is kind of way I like to arrange large application. Code is compiling but I am getting error on web assembly side. I couldn't make out any thing from that, I guess it is because of it is unable to compile some F# type. I have created a repo to reproduce that [here](https://github.com/kunjee17/TestBolero) . 

It would be great if someone can have a look at it. Or at least guide to debug the code.

**Comment by granicz** [comment]
For a start, you are missing the HTML template file(s) and `wwwroot` from the repo.

**Comment by kunjee17** [comment]
Sorry @granicz . git ignored has royally ignore my `wwwroot` folder again. I have add it back.

**Comment by Tarmil** [comment]
Ah I see the problem. `cond` is very limited, unfortunately: you can only pass either a boolean or a union. Here you're trying to pass a pair of unions, and that fails.

**Comment by kunjee17** [comment]
@tarmil is there anyway I can create by pass. Or is there any other way I can have scalability I'm looking for. Because this is very general way I arrange code in all my Elm style application be it Fable or Fabulous. ?

**Comment by kunjee17** [comment]
@granicz @Tarmil I was also curious about the limitation. If all F# code is getting compiled down to webassembly why there is limitation? 

And is there any documentation mentioning this or any other limitations ?

**Comment by granicz** [comment]
For the limitation around `cond`, see the "Conditional elements" subsection under https://fsbolero.io/docs/HTML

Also, to be precise, no F# code is getting translated to WASM, instead it's executed on a WASM-based runtime (Blazor). Blazor will eventually also target WASM.

**Comment by kunjee17** [comment]
@granicz Got your point. Thanks. I ll have a look. It would be great if you also can comment on architecture in my sample. It that right way to move forward or I should be correcting it. What correction would be required ?

**Comment by Tarmil** [comment]
A quick technical explanation on the reason *why* there is such a limitation. It comes down to the fact that Blazor's renderer was designed for content that is compiled from .razor files. If you look at the .g.cs file generated for a .razor, you'll it's a series of instructions such as "OpenElement", "AddAttribute", etc. Each of these instructions has a sequence number, and these sequence numbers are used by the renderer to determine exactly what needs to be inserted into and removed from the DOM. For example, when there is a conditional, the instructions in the `then` branch have different sequence numbers to the instructions in the `else` branch. In Bolero, we generate the sequence numbers on-the-fly, so we can't differentiate between branches of an `if` or `match`. Instead we need an explicit `cond` to be able to generate correct sequence numbers.

What `cond` does is look at `N` = how many cases your union type has, and `K` = which case the provided value is. It renders the provided content with sequence number `previousNumber + K`, and returns `previousNumber + N` to be used as `previousNumber` by the next instruction. That's why it only works with a union value (or a boolean, in which case N = 2 and K = 1 for true and 2 for false).

So a direct way to make your code work is turn your match on a pair of unions into nested `cond`s:

```fsharp
cond model.page <| function
| Home -> Home.homePage dispatch
| Counter ->
    cond model.pageModel <| function
    | CounterModel m -> Counter.counterPage m (CounterMsg >> dispatch)
    | _ -> failwith "wrong model page combination"
| Data ->
    cond model.pageModel <| function
    | DataModel m ->
        cond m.signedInAs <| function
        | Some username -> Data.dataPage m username (DataMsg >> dispatch)
        | None -> Data.signInPage m (DataMsg >> dispatch)
    | _ -> failwith "wrong model page combination"
```

Now, we can see that these new nested `cond`s have the same shape: in one case they render something, and in all other cases they fail. But if they render anything, it's always the same thing. So they don't actually need `cond`: you can use `match` for them as a slight optimization.

More generally about the problem you're solving, I've been thinking about how to handle page-specific models. Right now, what you're doing is pretty much the only way to have them while using `Router.infer`. But I think we can do better. We should be able to extend `Router.infer` to be able to include both the route and the model in the same union. I don't quite know how yet though.

**Comment by kunjee17** [comment]
@Tarmil thanks for explanation. I kind of getting your point. Happy to help to make this possible. Or may be we can come up with something which allows me to switch pages and also communicate with other components.

**Comment by kunjee17** [comment]
@Tarmil @granicz one more question. There is one more pattern in Elm architecture. Instead of having page model as optional type, they have all page model loaded as big fat object. 
```
type PageModel = A of A.Types.Model | B of B.Types.Model
type Model = {
   Page : Page
   PageModel : PageModel
}
// instead of above we will have something like this

type Model. = {
   Page : Page
   A : A.Types.Model
   B : B.Types.Model
}
```

I did go in this routes but if model is so nested or deep down then changing properties are very slow. But that was fable (JavaScript), here it is web assembly so it should hold. What do you guys think ?

> Above pattern is heavily used in Redux (angular and react both) (as they don't have option type they keep adding to global state)

**Comment by Tarmil** [comment]
Sorry for not answering this earlier, but: yes, putting the model in the main record is also a possibility. It depends on what behavior you want. Say the user goes to page A, touches a bunch of things so that A.Model is changed, then goes to page B, then again to page A. Should they then get the A.Model that they changed earlier, or a fresh new model? It depends on the application. It may even depend on the page within the same application. If you want them to get the modified A.Model, then you should put it in the main record. If you want them to get a fresh model, then you should put it in a union.
