### ISSUE TITLE
Template Provider mangles non-ASCII

### ISSUE THREAD

**Issue by laenas** [fsbolero/Bolero#83]
When a template contains non-ASCII characters, it looks like the Template Provider mangles those characters.  This is easily reproduced by adding non-ASCII glyphs - for example ÆØÅ - to a template and then viewing that template in the browser.

**Comment by BentTranberg** [comment]
Is this the problem with non-unicode source files that we've seen before? If so, easily solved by saving the file as unicode. In Visual Studio, open the file, then `Save As`, select the dropdown on the `Save` button, select `Save with Encoding`, choose `Unicode (UTF-8 with signature) - Codepage 65001` - probably the second entry in the list. And overwrite the file. (If this makes your VCS think you're overwriting/replacing the file rather than modifying it, then somehow solve that too before committing, so you don't get a bad history of the file.)

**Comment by laenas** [comment]
Indeed, that appears to have been the issue!  Cheers!
