### ISSUE TITLE
attribute support for ecomp

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#87]
Right now we use **ecomp** to create elmish components. However **ecomp** does not take any attributes. Especially when used with collections, using **key** attribute is recommended. So perhaps we should add an overload to this function such as **ecomWithAttr**.

**Comment by OnurGumus** [comment]
And above issue brought up another issue that there is no forEach equivalent for attributes in order to preserve the structure.

**Comment by Tarmil** [comment]
Good point. In fact I'm considering introducing a breaking change so that `ecomp` would always take a list of attributes.

Regarding `forEach` for attributes, unfortunately it wouldn't map properly to the underlying Razor renderer instructions. The only way to have an attribute that may or may not be present is to always include it and give it a value of either `null` or `false` when it should be absent.

**Comment by granicz** [comment]
+1 on `ecomp` taking attributes, even with the breaking change.
